### PR TITLE
Build multi-arch docker images

### PR DESCRIPTION
**Pull request by prabhu43**
Signed-off-by: Prabhu Jayakumar <j.prabhu91@gmail.com>

Fixes flyteorg/flyte#2935

### CODE REVIEW

**Comment by eapolinario** [comment]
@evalsocket , what's the best way to test this change?

**Comment by evalsocket** [comment]
@prabhu43 Please create a draft PR in flyteadmin/propeller, You just need to add your branch name here https://github.com/flyteorg/flyteadmin/blob/master/.github/workflows/checks.yml#L23, And then please first check all the PR checks

For the Merge pipeline, please fork the admin and make all the changes needed for using your branch and then test. 

cc: @eapolinario

**Comment by prabhu43** [comment]
Hi @evalsocket 
I forked this repo and worked on it. Shall I refer forked repo "prabhu43/flytetools" in the separate branch in flyteadmin ?

**Comment by prabhu43** [comment]
@evalsocket Do you mean checks should run in the fork itself? What secret should I add in the fork of flyteadmin?

**Comment by evalsocket** [comment]
Please add these secrets https://github.com/flyteorg/flyteadmin/blob/master/.github/workflows/checks.yml#L71-L72

**Comment by wild-endeavor** [comment]
this has been fixed.  thanks!

**Pull request closed without merging**
